spring.application.name=ai-weather-assistant

server.port=8081
server.error.include-message=always
server.error.include-binding-errors=always

weather.api.key=dc41db90aef83176b044a7088c125732

comfyui.url=http://localhost:8188
comfyui.checkpoint=sd_xl_base_1.0.safetensors
spring.web.resources.static-locations=classpath:/static/

spring.datasource.url=jdbc:h2:file:./skyvision-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update